name: CI

on:
  push:
    branches:
      - main
  pull_request:


env:
    CI: true

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun ci
